const data = [
    {
      id: 1,  
      game: "Pokemon Blue",
      console: "Game Boy",
      stock: 5,
      price: 89.99,
      thumbnail: require("./assets/pokemon-blue.jpg"),
      description: "What we have here is more than a game. It’s a piece of history. This is the blue Game Boy cartridge that sparked an international phenomenon which continues to this day. This is where Pokemon began. Back before the smart phone app, before there were over two decades of sequel games, mountains of merchandise, a massively popular card game, and dozens of feature films, Pokemon was just a Nintendo Game Boy title. Pokemon Blue Version took the best elements of Japanese RPG games, but added a few revolutionary ideas that would redefine the genre. Rather than just fighting monsters, it let you catch them, train them, and most importantly, trade them with other players. Pokemon was a game that literally brought people together. Pokemon Blue Version was launched alongside Pokemon Red Version, and both titles had exclusive critters. So, the only way anyone could catch all 151 original Pokemon was through teamwork. Blue Version featured the incredible Magmar, Pinsir, Vulpix, and Victreebel, along with seven other unique Pokemon that were nowhere to be found in the Red Version. But, more importantly, it contained an adventure that shaped a generation. In the game, you’re a bright-eyed youth, looking to become the greatest Pokemon Trainer in the world. However, eight gym leaders, the elite four, an organized crime syndicate, and your lifelong rival will all need to be defeated before you can claim that prestigious title. It’s a story that was shared by millions, but experienced differently by every player. No two people had exactly the same team of Pokemon or went about training them in exactly the same way. That was all you. And it can be again. Pokemon is always waiting to be revisited by those who want to be the very best, like no one ever was, both young and old alike. 100 authentic Nintendo product. GameBoy game cartridge only. All DK's classic used games are cleaned, tested, 100% authentic, guaranteed to work and backed by a 120 day warranty. Original Game Boy games will play on the original GameBoy, Game Boy Color, and Game Boy Advance systems.",
      condition: 'used',
      categoryId: 1
    },
    {
    id: 2,  
    game: "Pokemon Yellow",
    console: "Game Boy",
    stock: 5,
    price: 89.99,
    thumbnail: require("./assets/pokemon-yellow.jpg"),
    description: "Pokemon Yellow Version is essentially the Special Edition of Pokemon Red and Blue Version. It took the formula of both hit games and added a ton of great new features. For the first time ever, Pokemon was fully compatible with the Game Boy Color, allowing for all 151 critters to have their own unique color schemes. Additionally, every single Pokemon got a graphic overhaul to appear more like they did in the hit cartoon show and official game artwork. In fact, Yellow Version does a lot to feel more like the cartoon. Pikachu was now your default starting Pokemon, and rather than sit in a Pokeball, it literally walks beside you for the entire game. Even the series’ Team Rocket antagonists, Jessie and James, make cameos. New trainers and fresh challenges awaited anyone who was brave enough to explore this freshly remixed world of Pokemon. Added goodies like the secret Surfing Pikachu mini-game did a lot to distinguish this series entry from its predecessors, and offer what is hands down the best way to experience the original Pokemon epic.100% authentic Nintendo product. GameBoy game cartridge only. All DK's classic used games are cleaned, tested, 100% authentic, guaranteed to work and backed by a 120 day warranty.Original Game Boy games will play on the original GameBoy, Game Boy Color, and Game Boy Advance systems.",
    condition: 'used',
    categoryId: 1
    
  },
    {
    id: 3,  
    game: "Pokemon Gold",
    console: "Game Boy Color",
    stock: 5,
    price: 74.99,
    thumbnail: require("./assets/pokemon-gold.jpg"),
    description: "100% authentic Nintendo product. GameBoy Color game cartridge only. All DK's classic used games are cleaned, tested, 100% authentic, guaranteed to work and backed by a 120 day warranty. Original Game Boy Color games will play on the original Game Boy Color, and Game Boy Advance systems.", 
    condition: 'used',
    categoryId: 1
      },
     {
    id: 4,  
    game: "Mario Kart Super Circuit",
    console: "Game Boy Advance",
    stock: 5,
    price: 40.99,
    thumbnail: "https://cdn11.bigcommerce.com/s-ymgqt/images/stencil/320w/products/27619/35809/s-l1000_5__55605.1662152023.jpg?c=2",
    description: "Mario Kart Super Circuit - Game Boy Advance Game only. Great condition. All DK's classic used games are cleaned, tested, 100% authentic, guaranteed to work, and backed by a 120 day warranty.", 
    condition: 'used',
    categoryId: 2,
      },
     {
    id: 5,  
    game: "Super Mario Advance 4 - Super Mario Bros 3",
    console: "Game Boy Advance",
    stock: 5,
    price: 44.99,
    thumbnail: "https://cdn11.bigcommerce.com/s-ymgqt/images/stencil/320w/products/27716/18823/Game-GBAdvance-SMA4SMB3-2__76686.1661978654.jpg?c=2",
    description: "The original Super Mario Bros. 3 for the Nintendo Entertainment System my well be the greatest game Nintendo ever produced. With 9 enormous worlds spread out across 90 levels, each packed with all new enemies, power-ups, and brutal bosses, it was a video game masterpiece. So, what happens when you take the biggest game on the NES and remake it 15 years later for the Game Boy Advance? You get a video game for the ages! Super Mario Advance 4 Super Mario Bros. 3 took everything that was great about the original and lovingly remastered every last pixel with state of the art technology. A 256 color display allowed for visual fidelity that surpassed even the Super Nintendo. Dual 8-bit DAC Stereo Sound created a soundtrack that would have been unimaginable for the original NES. Super Mario Advance 4 Super Mario Bros. 3 was the first time a system could realize everything that game wanted to be. However, the improvements didn’t just stop with the games souped up specs. Super Mario Advance 4 Super Mario Bros. 3 included the addition of a much needed save feature. Back on the NES, players had to beat the toughest Mario game ever created in one sitting. However, the remake allowed you to take a break from its action whenever you needed a breather. And if you were lucky enough to have a Nintendo e-Reader, special E-Cards unlocked up to 32 additional stages made exclusively for the Game Boy Advance. Other E-Cards gave Mario special power-ups from his other adventures, like the Cape Feather from Super Mario World for the SNES, and projectiles from Super Mario Bros. 2. This mashup of incredible gameplay from across Mario’s entire history made Super Mario Advance 4 Super Mario Bros. 3 the ultimate celebration of over two decades of gaming perfection. This Mario title has all the polish that modern gamers have come to expect, but still includes all old school challenge that it dished out on the NES.", 
    condition: 'used',
    categoryId: 2,
      },

     {
    id: 6,  
    game: "Legend Of Zelda - Phantom Hourglass",
    console: "Nitendo DS",
    stock: 5,
    price: 56.99,
    thumbnail: "https://cdn11.bigcommerce.com/s-ymgqt/images/stencil/320w/products/26847/17895/Game-DS-ZeldaPH-2__34367.1662045273.jpg?c=2",
    description: "Includes original Nintendo DS game cartridge and may include case and manual. All Nintendo DS games play on the Nintendo DS, DS Lite, and 3DS systems. All DK's games are in good used condition and are cleaned, tested, 100% authentic, guaranteed to work, and backed by our 120 day warranty.", 
    condition: 'used',
    categoryId: 3,
      },

    {
    id: 7,  
    game: "Kirby's Dream Land",
    console: "Game Boy",
    stock: 5,
    price: 56.99,
    thumbnail: "https://cdn11.bigcommerce.com/s-ymgqt/images/stencil/80w/products/27008/18053/Game-GameBoy-KDL-2__62966.1661980294.jpg?c=2",
    description: "Original Nintendo Gameboy cartridge only. All classic used games are cleaned, tested, 100% authentic, guaranteed to work and backed by a 120 day warranty. All original Game Boy games will play on the original Game Boy and play in color on the Game Boy Color and Advance systems.", 
    condition: 'used',
    categoryId: 1,
      },

    {
    id: 8,  
    game: "Donkey Kong Country",
    console: "Game Boy Color",
    stock: 5,
    price: 29.99,
    thumbnail: "https://cdn11.bigcommerce.com/s-ymgqt/images/stencil/320w/products/27821/18932/Game-GBColor-DKC-2__51783.1661968519.jpg?c=2",
    description: "Donkey Kong Country - Game Boy Color original Nintendo cartridge only. Great condition and works like new. Game Boy Color games will play on the original Nintendo Game Boy Color, Advance, SP, and DS systems.", 
    condition: 'used',
    categoryId: 1,
      },

       {
    id: 9,  
    game: "Pokémon Pearl",
    console: "Nintendo DS",
    stock: 5,
    price: 89.99,
    thumbnail: "https://cdn11.bigcommerce.com/s-ymgqt/images/stencil/320w/products/26808/17853/Game-DS-PokePearl-2__45197.1662146094.jpg?c=2",
    description: "Includes original Nintendo DS game cartridge and may include case and manual. All Nintendo DS games play on the Nintendo DS, DS Lite, and 3DS systems. All DK's games are in good used condition and are cleaned, tested, 100% authentic, guaranteed to work, and backed by our 120 day warranty.", 
    condition: 'used',
    categoryId: 3
      },

      {
    id: 10,  
    game: "Castlevania - Portrait Of Ruin",
    console: "Nintendo DS",
    stock: 5,
    price: 36.99,
    thumbnail: "https://cdn11.bigcommerce.com/s-ymgqt/images/stencil/320w/products/37382/27832/Castlevania_Portrait__38323.1659991769.jpg?c=2",
    description: "Includes original Nintendo DS game cartridge and may include case and manual. All Nintendo DS games play on the Nintendo DS, DS Lite, and 3DS systems. All DK's games are in good used condition and are cleaned, tested, 100% authentic, guaranteed to work, and backed by our 120 day warranty.", 
    condition: 'used',
    categoryId: 3,
      },

      {
    id: 11,  
    game: "Pokémon Leaf Green",
    console: "Game Boy Advance",
    stock: 5,
    price: 120.99,
    thumbnail: "https://cdn11.bigcommerce.com/s-ymgqt/images/stencil/80w/products/27673/40551/poke-leaf-green__39901.1662040446.jpg?c=2",
    description: "This is the original Pokemon Adventure, remastered and reimagined for the Game Boy Advance! The GBA’s full color graphics, cinematic aspect ratio, and improved audio made for a Pokemon adventure like no other. A grand total of 386 Pocket Monsters waited to be caught, trained, and battled in this massive Pokemon epic! It’s plot is a remake of the story from Pokemon Red, Blue, and Yellow versions. You are a kid from the sleepy suburbs of Palette Town, who dreams of being the very best, like no one ever was. And, once you turn ten years old allowing you to get a Pokemon trainer’s License, you set out to show the world what you’ve got. Along the way you butt heads with your lifelong rival, topple Team Rocket, and crush the elite four to take your rightful place as a Pokemon Master. However, after reaching the conclusion of the original games’ story, Leaf Green offered a ton of brand new adventures! The Sevii Islands contained a host of new Pokemon and fresh perils for you to discover. Classic Pokemon could learn hundreds of new moves, wield dozens of equippable items, and had access to the abilities from Ruby and Sapphire Versions to allow for an unprecedented degree of customization for your favorite team of Pokemon. Add onto that the inclusion of the 2 v 2 battle system that pit four Pokemon against each other at once, and you could now experience the most challenging Pokemon battles to date! Pokemon Leaf Green Version is a remastered classic that proved Pokemon had worlds of potential that had yet to be explored, while setting the bar for all the games that followed it.", 
    condition: 'used',
    categoryId: 2,
      },

       {
    id: 12,  
    game: "Pokémon Sapphire",
    console: "Game Boy Advance",
    stock: 5,
    price: 139.99,
    thumbnail: "https://cdn11.bigcommerce.com/s-ymgqt/images/stencil/320w/products/27676/18778/Game-GBAdvance-PokSapph-2__42193.1662040435.jpg?c=2",
    description: "Pokemon Sapphire Version was the single best selling Game Boy Advance title for a reason: it was awesome. It would have been easy for Nintendo to make up a handful of new Pokemon and basically just release a digitally upgraded rehash of the last six games. However, Pokemon Sapphire Version went above and beyond all expectations. It started from a blank slate. The original 251 Pokemon were almost completely absent, as you explored the all new land of Hoenn, where ancient magic and mysticism still flourished. It was a region where towering metropolises sat alongside mausoleums that literally filled mountains, and mysterious stone towers rose above the clouds. To compliment this wondrous new territory were 135 completely new Pokemon that forced players to forget everything they knew about Pokemon, and rediscover the game all over again. New battle mechanics like Pokemon Abilities and 2 v 2 matches revolutionized the series’ core gameplay. And if you wanted to experience the ultimate Pokemon challenge, the Battle Tower was always open for business. New gadgets, gear, and Pokemon abilities allowed you to run across the fields of Hoenn, plunge to the bottom of the sea, and BMX jump your bicycle over ravines, for entirely new worlds of exploration. The game’s story also set a new benchmark for the series. Yes, your dream was still to defeat eight gyms, and conquer the Elite Four to become a Pokemon Master. However, this time around all of that took backseat to a narrative where you gradually learned of a secret society’s plot to awaken a primal beast capable of ending the world. Naturally, you are the only person capable of thwarting this calamity, meaning the stakes had never been higher. Pokemon Sapphire Version was a game that rose to the task of being an adventure for a new generation of gamers. It’s a masterpiece in every sense of the word, and it’s guaranteed to make you fall in love with the world of Pocket Monsters all over again.", 
    condition: 'used',
    categoryId: 2,
      },

       {
    id: 13,  
    game: "Mario Kart - Super Circuit",
    console: "Game Boy Advance",
    stock: 5,
    price: 44.99,
    thumbnail: "https://cdn11.bigcommerce.com/s-ymgqt/images/stencil/320w/products/27619/35809/s-l1000_5__55605.1662152023.jpg?c=2",
    description: "Mario Kart Super Circuit - Game Boy Advance Game only. Great condition. All DK's classic used games are cleaned, tested, 100% authentic, guaranteed to work, and backed by a 120 day warranty.", 
    condition: 'used',
    categoryId: 2,
      },

      {
    id: 14,  
    game: "Pokémon SoulSilver",
    console: "Nintendo DS",
    stock: 5,
    price: 219.99,
    thumbnail: "https://cdn11.bigcommerce.com/s-ymgqt/images/stencil/320w/products/37383/27834/pokemon_soul_silver__58005.1662151195.jpg?c=2",
    description: "Includes original Nintendo DS game cartridge and may include case and manual. All Nintendo DS games play on the Nintendo DS, DS Lite, and 3DS systems. All DK's games are in good used condition and are cleaned, tested, 100% authentic, guaranteed to work, and backed by our 120 day warranty.", 
    condition: 'used',
    categoryId: 3,
      },

      {
    id: 15,  
    game: "Diddy Kong Racing DS",
    console: "Nintendo DS",
    stock: 5,
    price: 19.99,
    thumbnail: "https://cdn11.bigcommerce.com/s-ymgqt/images/stencil/175x175/products/31439/22797/Diddy_Kong_Racing_DS__99360.1.jpg",
    description: "Includes original Nintendo DS game cartridge and may include case and manual. All Nintendo DS games play on the Nintendo DS, DS Lite, and 3DS systems. All DK's games are in good used condition and are cleaned, tested, 100% authentic, guaranteed to work, and backed by our 120 day warranty.", 
    condition: 'used',
    categoryId: 3,
      },

      
      {
    id: 16,  
    game: "Grand Theft Auto - Chinatown Wars",
    console: "Nintendo DS",
    stock: 5,
    price: 39.99,
    thumbnail: "https://cdn11.bigcommerce.com/s-ymgqt/images/stencil/320w/products/26750/17793/Game-DS-GTACW-2__39742.1661455484.jpg?c=2",
    description: "Includes original Nintendo DS game cartridge and may include case and manual. All Nintendo DS games play on the Nintendo DS, DS Lite, and 3DS systems. All DK's games are in good used condition and are cleaned, tested, 100% authentic, guaranteed to work, and backed by our 120 day warranty.", 
    condition: 'used',
    categoryId: 3,
      },

        {
    id: 17,  
    game: "Wario Master Of Disguise",
    console: "Nintendo DS",
    stock: 5,
    price: 39.99,
    thumbnail: "https://cdn11.bigcommerce.com/s-ymgqt/images/stencil/320w/products/31603/23392/wario_disguise__56481.1662149928.jpg?c=2",
    description: "Includes original Nintendo DS game cartridge and may include case and manual. All Nintendo DS games play on the Nintendo DS, DS Lite, and 3DS systems. All DK's games are in good used condition and are cleaned, tested, 100% authentic, guaranteed to work, and backed by our 120 day warranty.", 
    condition: 'used',
    categoryId: 3,
      },

      {
    id: 18,  
    game: "Mario Golf",
    console: "Game Boy Color",
    stock: 5,
    price: 37.99,
    thumbnail: "https://cdn11.bigcommerce.com/s-ymgqt/images/stencil/320w/products/27864/18974/Game-GBColor-MarioGolf-2__07583.1661547127.jpg?c=2",
    description: "Mario Golf - Game Boy Color Original Nintendo Game Boy Color cartridge only. Great condition and works like new. Game Boy Color games will play on the original Nintendo Game Boy Color, Advance, SP, and DS systems.", 
    condition: 'used',
    categoryId: 1,
      },
  ];

  module.exports = {
    data,
  }

